site_title = "MyArxiv"
limit_days = 7
cache_url = "https://zheyuanlai.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "stat.ML"
title = "Machine Learning"

[[sources]]
limit = 150
category = "stat.CO"
title = "Computation"

[[sources]]
limit = 150
category = "math.OC"
title = "Optimization and Control"

[[sources]]
limit = 150
category = "math.PR"
title = "Probability"

[[sources]]
limit = 150
category = "math.NA"
title = "Numerical Analysis"

[[sources]]
limit = 150
category = "math.MP"
title = "Mathematical Physics"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
